data:
    dataset: "Hdr"
    image_size: 128
    inf_size: 512
    channels: 3
    num_workers:  16
    data_dir: "./"
    conditional: True

model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 1
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

training:
    patch_n: 8
    batch_size: 8
    n_epochs: 300000
    n_iters: 3000000
    snapshot_freq: 10000
    validation_freq: 10000

sampling:
    batch_size: 8
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001
